### ISSUE TITLE
author linked search - phrase search fails

### ISSUE THREAD

**Issue by bmckinney** [ebsco/edsapi-ruby#45] opened 2017-07-11 11:52 UTC
Question about author linked searches:  when the author name has a role term following it, a phrase search fails.  e.g. edsswe__edsswe_oai_DiVA_org_liu_134775  A keyword search gets results, but more than it should.  Is there a separate index we should be looking at here? I notice the native UI doesn't link these authors.

**Comment by bmckinney** [comment] 2017-07-18 17:15
Note: available in two databases: edsgao__edsgcl_476314180 and edsswe__edsswe_oai_DiVA_org_liu_134775.

The second one has author affiliations and roles within the author section.

**Comment by drh-stanford** [comment] 2017-07-19 20:57
Duplicate of https://github.com/ebsco/edsapi-ruby/issues/51?

**Comment by ellieebsco** [comment] 2021-04-20 14:30
Closing, see note in https://github.com/ebsco/edsapi-ruby/issues/51

**Closed as completed by ellieebsco** 2021-04-20 14:30 UTC
Labels: bug, blacklight, data-question
