### ISSUE TITLE
How to specify limiters FT and FT1 together

### ISSUE THREAD

**Issue by jgreidy** [ebsco/edsapi-ruby#98] opened 2020-09-23 16:08 UTC
As a patron, I want to be sure I see the same results in blacklight as I see when I get to the EDS interface. Our eds profile is set up with limiters 'Full text' and 'Available in Library Collection' checked off by default, so I want to simulate the same situation using edsapi-ruby.
When I try to specify both limiters, only one will 'take'. Here's my test:

```
def limiter_test(session)
        q = "cancel culture"
        start = 0
        per_page = 3
        sqs = [
            {query: q, page: start, results_per_page: per_page},
            {query: q, page: start, results_per_page: per_page, limiters: ['FT1:Y']},
            {query: q, page: start, results_per_page: per_page, limiters: ['FT1:Y', 'FT:Y']},
            {query: q, page: start, results_per_page: per_page, limiters: ['FT1:Y', 'FT:Y', 'RV:Y']}
        ]
         sqs.each do |sq|
            msg = ['******************']
            response = session.search(sq)
            msg << 'sq: ' + sq.inspect
            msg << 'total_hits: ' + response.stat_total_hits.to_s
            applied_limiters = response.applied_limiters.map{|hash| hash['Id']}
            msg << 'limiters: ' + response.applied_limiters.inspect
            response.records.each do |rec|
                msg << rec.eds_title().to_s
            end
            msg << '******************'
            puts msg.to_yaml
        end
    end
```
and here is the output:
```
- "******************"
- 'sq: {:query=>"cancel culture", :page=>0, :results_per_page=>3, "page"=>1}'
- 'total_hits: 4863'
- 'limiters: []'
- 'How I Ran Afoul of Campus Cancel Culture: My experience with the Goldman School
  at Berkeley.'
- 'Racist call-outs and cancel culture on Twitter: The limitations of the platform’s
  ability to define issues of social justice'
- "'Krazy Kripples' and the Transformative Body Politics of Disability and Race: Watching
  South Park the Age of 'Cancel Culture'"
- "******************"
---
- "******************"
- 'sq: {:query=>"cancel culture", :page=>0, :results_per_page=>3, :limiters=>["FT1:Y"],
  "page"=>1}'
- 'total_hits: 4001'
- 'limiters: [{"Id"=>"FT1", "LimiterValuesWithAction"=>[{"Value"=>"y", "RemoveAction"=>"removelimitervalue(FT1:y)"}],
  "RemoveAction"=>"removelimiter(FT1)"}]'
- 'How I Ran Afoul of Campus Cancel Culture: My experience with the Goldman School
  at Berkeley.'
- 'Racist call-outs and cancel culture on Twitter: The limitations of the platform’s
  ability to define issues of social justice'
- "'Krazy Kripples' and the Transformative Body Politics of Disability and Race: Watching
  South Park the Age of 'Cancel Culture'"
- "******************"
---
- "******************"
- 'sq: {:query=>"cancel culture", :page=>0, :results_per_page=>3, :limiters=>["FT1:Y",
  "FT:Y"], "page"=>1}'
- 'total_hits: 4000'
- 'limiters: [{"Id"=>"FT", "LimiterValuesWithAction"=>[{"Value"=>"y", "RemoveAction"=>"removelimitervalue(FT:y)"}],
  "RemoveAction"=>"removelimiter(FT)"}]'
- 'How I Ran Afoul of Campus Cancel Culture: My experience with the Goldman School
  at Berkeley.'
- 'Racist call-outs and cancel culture on Twitter: The limitations of the platform’s
  ability to define issues of social justice'
- "'Krazy Kripples' and the Transformative Body Politics of Disability and Race: Watching
  South Park the Age of 'Cancel Culture'"
- "******************"
---
- "******************"
- 'sq: {:query=>"cancel culture", :page=>0, :results_per_page=>3, :limiters=>["FT1:Y",
  "FT:Y", "RV:Y"], "page"=>1}'
- 'total_hits: 362'
- 'limiters: [{"Id"=>"FT", "LimiterValuesWithAction"=>[{"Value"=>"y", "RemoveAction"=>"removelimitervalue(FT:y)"}],
  "RemoveAction"=>"removelimiter(FT)"}, {"Id"=>"RV", "LimiterValuesWithAction"=>[{"Value"=>"y",
  "RemoveAction"=>"removelimitervalue(RV:y)"}], "RemoveAction"=>"removelimiter(RV)"}]'
- 'Racist call-outs and cancel culture on Twitter: The limitations of the platform’s
  ability to define issues of social justice'
- "'Krazy Kripples' and the Transformative Body Politics of Disability and Race: Watching
  South Park the Age of 'Cancel Culture'"
- 'No Grand Pronouncements Here ... : Reflections on Cancel Culture and Digital Media
  Participation ...'
- "******************"
```

When I use both FT1 and FT together, only the later of the two gets applied, though another limiter, like RV, can be applied. Is this intentional?

I see this message about them being 'OR'ed together when used in conjunction: 
https://connect.ebsco.com/s/article/What-happens-if-I-select-both-the-Full-Text-Online-and-Available-in-Library-Collection-limiters-in-EBSCO-Discovery-Service?language=en_US

**Comment by efrierson** [comment] 2021-03-11 13:36
I've noted your feedback - the problem is in the underlying search service (as opposed to the gem), so I'm adding this commentary to the EBSCO Service Issue #28567.  I do this this will likely be resolved in a future iteration of the EDS API, and when that happens, we'll update the gem accordingly.  

Thanks for your feedback!

**Closed as completed by efrierson** 2021-03-11 13:36 UTC
