### ISSUE TITLE
Non-UTF8 characters returned

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#52] opened 2017-07-20 21:15 UTC
We're seeing broken characters in some of the data the EDS gem is returning, like so (id = `edb__47529049`):

```
"eds_authors": [
"V.  DÃ©neux",
"Y.  Cadoret",
"S.  Hervier",
"D.  Monceau"
],
```

**Comment by bmckinney** [comment] 2017-07-24 15:28
looks like bad windows-1252 encoding:
"DÃ©neux".encode("Windows-1252").force_encoding("UTF-8")
 => "Déneux"

**Comment by drh-stanford** [comment] 2017-07-24 18:12
so does that mean it's a data-issue for that one record? or is this a systemic issue? i have more examples (`agr__IND605569661`)

**Comment by drh-stanford** [comment] 2017-08-03 22:14
Here's another example (`agr__IND605208561`) -- it's the same dbid so maybe that one is having a problem?

![screen shot 2017-08-03 at 3 12 54 pm](https://user-images.githubusercontent.com/1861171/28946142-4d99e6b8-785e-11e7-89d8-edcaed19d914.png)

**Comment by efrierson** [comment] 2021-03-06 22:52
This remains an issue.  I've opened a case for this, as the issue is with the source data in our partner database AGRIS.  The same article appears fine from other partners (JSTOR, for example).  Since this is a data issue, you can get updates on it from our support team referencing case #4568368.  Closing here since this is not a gem issue.

**Closed as completed by efrierson** 2021-03-06 22:52 UTC
Labels: bug, data-question
